### ISSUE TITLE
No tray icon for plasma 5 on archlinux

### ISSUE THREAD

**Issue by Grokafar** [andrew-bibb/cmst#118]
No systray icon appears in the plasma5's tray, whatever the color choosen. With the current release, only the disconnected icon can be seen, the others appear  invisible. With the current git version (febb7dc) none can be seen.

EDIT : I can see all icon with --fake-tranparency 0xRRVVBB  but the icon is on a background, I post you two screenshots with ad without the start parameters

Color 0x5500ff --fake-tranparency 0x000000
![with](https://cloud.githubusercontent.com/assets/12222316/10821168/4845a4bc-7e51-11e5-9086-455dbd492a71.png)
Color 0x5500ff without fake transparency
![without](https://cloud.githubusercontent.com/assets/12222316/10821169/4847a668-7e51-11e5-8d6e-2bbd0f0ca1e8.png)

**Comment by hagabaka** [comment]
You are probably using the "Breeze" icon theme, and the icon is about the same color as your panel background. Instead you can set the icon theme to "Breeze Dark" in CMST preferences.

**Comment by andrew-bibb** [comment]
I just rebuilt and tested on my system, plus went through my backups up to 2 months ago seeing if I changed anything in the code.  Negative on both counts, wifi tray icons work on my system and I've not changed any code relating to the WiFi icons in the last 60 days.

The fact that it works with the fake transparency is curious (and at least gives you a work around for now).  You are getting the wifi icons but they seem to be completely transparent in your bar.  The fake transparency (the way I've implemented it) removes any real transparency from the icon.  This gives me a place to start.

It may be just as simple as running the icons through Imagemagik again with some different settings.  I already had to run them through once to clean them up because QT throws errors trying to read them if you don't. Maybe they got cleaned too far, and the most recent batch to go through definitely included all the WiFi icons (plus a couple of others).

**Comment by andrew-bibb** [comment]
Hagabaka,
Good suggestion but I'm afraid we've already tried that.  This thread actually started in the Arch Linux AUR site, and I was hoping it was something easy like that.  When it became evident it wasn't I suggested moving the discussion here since it is not really an AUR issue.

**Comment by andrew-bibb** [comment]
I really don't know if this is going to work for you or not, but I just uploaded new icons for the system tray with the alpha background matching the one icon that did work for you (connect_no).

Let me know if this does it and I'll start converting all the others, otherwise back to the drawing board.

**Comment by Grokafar** [comment]
I compiled with the new icons from github but I still seeing nothing. None of icons appear without the fake transparency even connected_no... I'll search by my side if I can find something. 
If you want information to debug let me know I'll give them to you.

**Comment by andrew-bibb** [comment]
I'm going to start building a KDE virtual machine to test it out at this end.  Pretty sure is is something with the alpha, just don't know what. I'm sure I'll be needing some information from you, but let me get that virtual machine running first.

**Comment by andrew-bibb** [comment]
Just giving an update as to where I am.  Not only was my Arch install in Virtualbox out of date, but Virtualbox itself was way out of date.  The version I had running would not deal with any of the new kernels (tried Kubuntu as well).  Anyway got VirtualBox reinstalled, Arch and KDE installed in that, and CMST built in KDE.  At the moment I'm not seeing any icons of any sort in the system tray, but I think that may be a setting I've not checked properly.  Anyway I'm at the point where I can start doing some real investigation as to what is going on.

**Comment by andrew-bibb** [comment]
Got it, but before that I wanted to mention that after my previous post I was able to duplicate the problems you were having with Plasma 5.  Seems the icons need to contain pixmaps in the ARGB32 format.  Fake transparency converts the icons to that format.

Code uploaded now should work for you.  It does here for both the internal and Breeze system theme icons.  Colorizing the internal icons also works.  This code is a bit temporary as I was trying lots of things and I now need to go back and clean up the mess.  The converting to ARGB32 code will still be there, maybe just not quite in the location it is now.

**Comment by Grokafar** [comment]
Well done,it works, the issue can be closed ! Thanks!
